manifest_version = "V2.0"

[package]
name = "termtris"
version = "1.9"
description = "Tetris game for terminals"
license = "GPL-3.0-or-later"
homepage = "http://nuclear.mutantstargoat.com/sw/termtris/"
maintainer = "YOSI Project"

[source]
url = "https://github.com/jtsiomb/termtris/archive/refs/tags/v1.9.tar.gz"
sha256 = "1aecc1de795185a70d550d3e8d3212d97ffd997af9796ab220e055e039443dbe"
size = 38007
strip_components = 1

[dependencies]
runtime = []
build = []
optional = []
conflicts = []

[recipe]
file = "build.toml"

[metadata]
architectures = ["any"]
os = ["linux"]